spring:
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
#    hibernate:
#      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/envers_app_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123

  flyway:
    locations:
    - db/migration
    - db/insertData
